### ISSUE TITLE
MSI directory cleanup: questions for Ali

### ISSUE THREAD

**Issue by mkosmala** [SnapshotSerengetiScienceTeam/DataManagement#37]
@aliburchard: Some questions for you so @palme516 and I can clean up the MSI directory structure: 

1. What are the access files in S5_weird_stuff? Do we need them?
2. Can you please delete S8backup if that's no longer needed?
3. What's are S1,S2,S3,S6 in AddToDB? (We don't have permission to look.)
4. What is the 'copyoutput' directory? (We don't have permission to look.)
5. Is directory 'Target' still used? Can we delete it?
6. Do we need 'prepped_data_products/PhotosForMichael' anymore? Meredith and I were talking about only keeping copies of images for collaborators around for as long as we needed them and then deleting them.

Thanks!

**Comment by aliburchard** [comment]
@mkosmala @palme516:

1. Access files were just field entry data, we don't need those files there.
2. Doing so now.
3. AddToDB images includes rolls that weren't incorporated into the Serengeti Live Database (because I couldn't add new rolls, and thus the importer didn't recognize them). Thus they were never sent to Zooniverse. I suspect that the S6 rolls in this folder were sent with S7? And I suspect that the S1-3 rolls will be marked in the database as never being sent to Z, but we need to check.
4.'copyoutput' is just the logs from when I copied and renamed files. these don't need to be on the shared directory unless you want them. I've currently moved them to my directory.
5. Nope, and done.
6. Agreed. nope and done.

I'll open an issue for checking the AddToDB rolls and close this one out.
